New lens distortion calibration software
alicevision/AliceVision pull request #1035
Opened 2021-05-05 08:43 UTC by fabiencastan

## Description

New software to calibrate the lens distortion parameters from an image of a checkerboard.

2021-05-05 08:45 UTC, fabiencastan commented on src/aliceVision/sfm/BundleAdjustmentCeres.cpp
> +        x_plus_delta[1] = x[1] + delta[posDelta];
``
```suggestion
        x_plus_delta[0] = x[0] + delta[posDelta];
```

2021-05-05 08:47 UTC, fabiencastan commented on src/aliceVision/sfm/BundleAdjustmentCeres.cpp
> +
```suggestion

    std::cout << "????????" << _focalRatio << std::endl;

```

2021-05-05 16:02 UTC, simogasp requested changes
I did a pass in the calibration module.
It's very hard to process these kinds of PRs, it's too big, even the browser struggles.
It is better to have PRs that are self-contained and focusing on a single feature. Here we have calibration, a new camera model and god knows what else.
If we want to keep the codebase in check we should avoid all this.
Just my thought.

2021-05-28 19:26 UTC, fabiencastan commented on src/aliceVision/calibration/checkerDetector.cpp
> +        if (candidates.back().score > 1e6)
I got a crash on `candidates.back()` as there is a pop_back just before.

2021-06-01 15:51 UTC, fabiencastan commented on src/aliceVision/camera/DistortionRadial.hpp
> +    const Eigen::MatrixXd ret = p * r * r;
k1 is not used?

2021-06-01 16:36 UTC, fabiencastan commented on src/software/utils/main_sfmTransfer.cpp
> +        for (auto & intrinsic : sfmData.getIntrinsics())
the std::pair of the map is temporary.

2021-06-01 21:03 UTC, merged