Update symbolic Bundle Adjustment
alicevision/AliceVision pull request #1060
Opened 2021-06-16 12:22 UTC by servantf

Update the symbolic bundle adjustment to be on par with updates of the classical bundle adjustment options.

2021-08-11 15:40 UTC, simogasp requested changes

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/sfm/liealgebra.hpp
> +inline Eigen::Matrix<double, 16, 16> d_inverse(const Matrix & source)
```suggestion
inline Eigen::Matrix<double, 16, 16> d_inverse(const Matrix4d & source)
```
If the size of the matrix (and the type) is to be known it's better to specify it

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/multiview/relativePose/Rotation3PSolver.cpp
> +        pn(2) = 1.0;
i think you can do
```suggestion
        Vec3 pn(p2d(0, i),  p2d(1, i), 1.0);
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/multiview/relativePose/Rotation3PSolver.cpp
> +    for (int i = 0; i < n; i++)
```suggestion
    for (Mat::Index i = 0; i < n; ++i)
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/multiview/relativePose/Rotation3PSolver.cpp
> +            {
```suggestion
    for(Mat::Index i = 0; i < n; ++i)
    {
        for(Mat::Index k = 0; k < 3; ++k)
        {
            for(Mat::Index l = 0; l < 3; ++l)
            {
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/multiview/relativePose/Rotation3PSolver.cpp
> +    Eigen::Matrix3d V = svd.matrixV();
```suggestion
    const Eigen::Matrix3d U = svd.matrixU();
    const Eigen::Matrix3d V = svd.matrixV();
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/multiview/relativePose/Rotation3PSolver.cpp
> +    robustEstimation::Mat34Model ret(R);
```suggestion
    const robustEstimation::Mat34Model ret(R);
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/multiview/relativePose/Rotation3PSolver.cpp
> +    Eigen::Matrix3d G = U * V.transpose();
```suggestion
    const Eigen::Matrix3d G = U * V.transpose();
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
> +        posDelta++;
```suggestion
        ++posDelta;
```
prefer preincrement

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
> +    Vec4 pth = pt.homogeneous();
```suggestion
    const Vec4 pth = pt.homogeneous();
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
> +    SE3::Matrix oTr = SE3::inverse(rTo);
```suggestion
    const SE3::Matrix oTr = SE3::inverse(rTo);
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
> +    if (scale < 1e-12) scale = 1.0;
```suggestion
    const double scale = _measured.scale < 1e-12 ? 1.0 : _measured.scale;
```

2021-08-11 15:40 UTC, simogasp commented on src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
> +    Vec2 pt_est = _intrinsics->project(T_pose3, cartesianpt, true);
```suggestion
    const geometry::Pose3 T_pose3(T.block<3,4>(0, 0));

    const Vec4 cartesianpt = _intrinsics->getCartesianfromSphericalCoordinates(pt);

    const Vec2 pt_est = _intrinsics->project(T_pose3, cartesianpt, true);
```

2021-08-17 07:22 UTC, fabiencastan commented on src/aliceVision/sfmData/Landmark.hpp
> +  IndexT referenceView = UndefinedIndexT;
I'm not sure what's the meaning of this variable.
Could you add documentation?
Also, I don't see any place where this value is set.

2021-08-17 07:47 UTC, fabiencastan commented on src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
> +class CostProjectionRelative : public ceres::CostFunction {
Needs doxygen doc

2021-08-17 07:47 UTC, fabiencastan commented on src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
> +class CostProjectionRelativeSimplified : public ceres::CostFunction {
Needs doxygen doc

2021-08-17 07:47 UTC, fabiencastan commented on src/aliceVision/sfm/BundleAdjustmentSymbolicCeres.cpp
> +class CostMotionConstantSpeed : public ceres::CostFunction {
Needs doxygen doc

2021-08-17 23:03 UTC, merged