Use assimp as mesh importer and exporter
alicevision/AliceVision pull request #1090
Opened 2021-08-04 12:52 UTC by servantf

Use assimp to be able to import and export mesh instead of custom code.

Currently just replacing the obj import and export function, but maybe updated later to be more generic

2021-08-04 16:58 UTC, simogasp requested changes
Maybe add the cmake code to build assimp like the other libs
```
    set(ASSIMP_TARGET assimp)
    set(ASSIMP_BUILD_OPTIONS -DASSIMP_BUILD_ASSIMP_TOOLS:BOOL=OFF -DASSIMP_BUILD_TESTS:BOOL=OFF)
    set(ASSIMP_AV_VERSION 5.0.1)
    set(ASSIMP_FILENAME v${ASSIMP_AV_VERSION}.tar.gz)
    ExternalProject_Add(${ASSIMP_TARGET}
            URL https://github.com/assimp/assimp/archive/${ASSIMP_FILENAME}
            DOWNLOAD_NAME assimp-${ASSIMP_FILENAME}
            PREFIX ${BUILD_DIR}
            BUILD_IN_SOURCE 0
            BUILD_ALWAYS 0
            SOURCE_DIR ${CMAKE_CURRENT_BINARY_DIR}/assimp
            BINARY_DIR ${BUILD_DIR}/assimp_build
            INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
            CONFIGURE_COMMAND ${CMAKE_COMMAND} ${CMAKE_CORE_BUILD_FLAGS} ${ASSIMP_BUILD_OPTIONS} -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR> <SOURCE_DIR>
            )
    set(ASSIMP_CMAKE_FLAGS -DAssimp_DIR:PATH=${CMAKE_INSTALL_PREFIX}/lib/cmake/assimp-${ASSIMP_AV_VERSION}/)
```
Verify the last line as I cannot check if it still installs assimp in a folder named `assimp-${ASSIMP_VERSION}`

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +        for (int i = 0; i < 4; i++)
```suggestion
        for (int i = 0; i < 4; ++i)
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +            for (int j = 0; j < 4; j++)
```suggestion
            for (int j = 0; j < 4; ++j)
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +            unsigned int meshId = node->mMeshes[idMesh];
```suggestion
            const auto meshId = node->mMeshes[idMesh];
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                aiVector3D v = mesh->mVertices[idPoint];
```suggestion
                const aiVector3D v = mesh->mVertices[idPoint];
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                pts.push_back(Point3d(v.x, v.y, v.z));
```suggestion
                pts.emplace_back(v.x, v.y, v.z);
```
requires to add the wrapper method to `StaticVector`

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                    double b = c.b * 255.0;
```suggestion
                    const double r = c.r * 255.0;
                    const double g = c.g * 255.0;
                    const double b = c.b * 255.0;
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                    _colors.push_back(aliceVision::rgb(r, g, b));
```suggestion
                    _colors.emplace_back(r, g, b);
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                    aiVector3D t = mesh->mTextureCoords[0][idPoint];
```suggestion
                    const aiVector3D t = mesh->mTextureCoords[0][idPoint];
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                    uvCoords.push_back(Point2d(t.x, t.y));
```suggestion
                    uvCoords.emplace_back(t.x, t.y);
```
requires adding the method to `StaticVector`

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                    aiVector3D n = mesh->mNormals[idPoint];
```suggestion
                    const aiVector3D n = mesh->mNormals[idPoint];
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                    normals.push_back(Point3d(n.x, n.y, n.z));
```suggestion
                    normals.emplace_back(n.x, n.y, n.z);      
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +            for (int idFace = 0; idFace < mesh->mNumFaces; idFace++)
```suggestion
            for (int idFace = 0; idFace < mesh->mNumFaces; ++idFace)
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                aiFace face = mesh->mFaces[idFace];
```suggestion
                const aiFace face = mesh->mFaces[idFace];
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                for (int idVertex = 0; idVertex < face.mNumIndices; idVertex++)
```suggestion
                for (int idVertex = 0; idVertex < face.mNumIndices; ++idVertex)
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                    unsigned int global_index = map_indices[index];
```suggestion
                    const unsigned int index = face.mIndices[idVertex];
                    const unsigned int global_index = map_indices[index];
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +        for (int idChild = 0; idChild < node->mNumChildren; idChild++)
```suggestion
        for (int idChild = 0; idChild < node->mNumChildren; ++idChild)
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Texturing.cpp
> +            for (int k = 0; k < 3; k++)
```suggestion
            for (int k = 0; k < 3; ++k)
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Texturing.cpp
> +            int uvId = p.first.second;
```suggestion
            const int vertexId = p.first.first;
            const int uvId = p.first.second;
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Texturing.cpp
> +            int triangleId = _atlases[atlasId][i];
```suggestion
            const int triangleId = _atlases[atlasId][i];
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Texturing.cpp
> +        for(int i = 0; i < _atlases[atlasId].size(); i++)
```suggestion
        for(int i = 0; i < _atlases[atlasId].size(); ++i)
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Texturing.cpp
> +                int uvId = mesh->trisUvIds[triangleId].m[k];
```suggestion
                const int vertexId = mesh->tris[triangleId].v[k];
                const int uvId = mesh->trisUvIds[triangleId].m[k];
```

2021-08-04 16:58 UTC, simogasp commented on src/aliceVision/mesh/Texturing.cpp
> +            for (int k = 0; k < 3; k++)
```suggestion
            for (int k = 0; k < 3; ++k)
```

2021-08-04 20:42 UTC, simogasp commented on src/aliceVision/mesh/Texturing.cpp
> +    if (_atlases.size() == 0)
```suggestion
    if (_atlases.empty)
```

2021-08-09 06:23 UTC, fabiencastan commented
Is there a way to add a message in the OBJ file that it has been generated with AliceVision and specify the version?
Currently it says only assimp and the version of assimp.

2021-08-09 06:24 UTC, fabiencastan approved these changes

2021-08-09 08:28 UTC, simogasp commented
> Is there a way to add a message in the OBJ file that it has been generated with AliceVision and specify the version?
> Currently it says only assimp and the version of assimp.

I think you can add it in the `aiMetadata`
https://assimp-docs.readthedocs.io/en/master/API/API-Documentation.html#_CPPv410aiMetadata

2021-08-09 08:41 UTC, simogasp commented on src/aliceVision/mesh/Mesh.cpp
> +                pts.push_back(Point3d(v.x, v.y, v.z));
I think adding this to `StaticVector` should work
```c++
    template< class... Args >
    void emplace_back( Args&&... args )
    {
        _data.emplace_back(std::forward<Args>(args)...);
    }
```

2021-08-09 09:36 UTC, fabiencastan commented
I'm merging it for now.
@servantf Can you check if we can add metadata in a new PR?

2021-08-09 09:37 UTC, merged

2021-08-09 11:03 UTC, servantf commented
There is no way to add metadata in obj files. 
aiMetadata are almost never exported but used for importers.
A solution may be to fork assimp and modify it ?