Panorama alignment with a reference camera
alicevision/AliceVision pull request #1334
Opened 2023-01-17 13:44 UTC by servantftechnicolor

2023-02-14 18:50 UTC, fabiencastan commented on src/software/utils/main_sfmTransform.cpp
> +IndexT getReferenceViewIndex(const sfmData::SfMData & sfmData, const std::string & transform)
getReferenceViewId

2023-02-14 18:50 UTC, fabiencastan commented on src/software/utils/main_sfmTransform.cpp
> +    IndexT refPoseId;
refViewId

2023-02-14 18:51 UTC, fabiencastan commented on src/software/utils/main_sfmTransform.cpp
> +            sorted_views.push_back(std::make_pair(t, v.second->getPoseId()));
sorted_views.push_back(std::make_pair(t, v.second->getViewId()));

2023-02-14 18:51 UTC, fabiencastan commented on src/software/utils/main_sfmTransform.cpp
> +        refPoseId = sfm::getViewIdFromExpression(sfmData, transform);
refViewId = sfm::getViewIdFromExpression(sfmData, transform);

2023-02-14 18:53 UTC, fabiencastan commented on src/software/utils/main_sfmTransform.cpp
> +  Eigen::Matrix3d ref_R_world = sfmData.getAbsolutePose(refPoseId).getTransform().rotation();
Eigen::Matrix3d ref_R_world = sfmData.getPose(sfmData.getView(refViewId)).getTransform().rotation();

2023-02-14 18:55 UTC, fabiencastan commented on src/software/utils/main_sfmTransform.cpp
> +        R = zeroX_R_world * R;
to move to a dedicated function in the library and not in the main here.

2023-02-14 18:56 UTC, fabiencastan requested changes
2 fixes needed

2023-02-17 11:53 UTC, fabiencastan commented on src/software/utils/main_sfmTransform.cpp
> +            sorted_views.push_back(std::make_pair(t, v.second->getPoseId()));
still getViewId ?

2023-02-20 10:18 UTC, cbentejac approved these changes
Tested on Linux with https://github.com/alicevision/Meshroom/pull/1876 on both pinhole and fisheye panoramas, with and without HDR.

For all the used datasets, the PR worked as intended (a rebase was needed, though).

2023-02-21 22:37 UTC, fabiencastan approved these changes

2023-02-21 22:37 UTC, merged