[panorama] force pyramid levels count in compositing
alicevision/AliceVision pull request #1369
Opened 2023-03-03 16:09 UTC by servantftechnicolor

[panorama] force pyramid levels count in compositing

2023-03-05 17:57 UTC, fabiencastan commented on src/software/pipeline/main_panoramaCompositing.cpp
> +        ("forcedLevelsCount, f", po::value<int>(&forcedLevelsCount)->default_value(forcedLevelsCount), "For multiband compositer, force a given number of levels in pyramid (0 for automatic)")
```suggestion
        ("forceMinLevels,f", po::value<int>(&forceMinLevels)->default_value(forceMinLevels), "For multiband compositer, force a minimum number of levels in the image pyramid (0 for automatic)")
```

2023-03-05 18:03 UTC, fabiencastan requested changes
It would be better if the option defines a min pyramid level value, instead of overriding the automatically determined number of pyramid levels.

2023-03-06 11:28 UTC, servantftechnicolor commented on src/software/pipeline/main_panoramaCompositing.cpp
> +        ("forcedLevelsCount, f", po::value<int>(&forcedLevelsCount)->default_value(forcedLevelsCount), "For multiband compositer, force a given number of levels in pyramid (0 for automatic)")
done

2023-03-07 15:06 UTC, fabiencastan commented on src/software/pipeline/main_panoramaCompositing.cpp
> +
```suggestion
    ALICEVISION_LOG_INFO("Estimated pyramid levels count: " << min_scale);

    if (forceMinPyramidLevels > min_scale)
    {
        min_scale = forceMinPyramidLevels;
        ALICEVISION_LOG_INFO("Forced pyramid levels count: " << min_scale);
    }

```

2023-03-09 18:50 UTC, fabiencastan approved these changes

2023-03-09 18:50 UTC, merged