[software] fix split dual fisheye
alicevision/AliceVision pull request #1378
Opened 2023-03-13 16:14 UTC by mugulmd

## Description

The `dualfisheye` split mode of the `aliceVision_split360Images` software is currently broken, as it only saves on disk two fully black images.
This problem seems to be related to the use of oiio image buffers for copying data.

In this PR, we replace the previous approach with a simpler one: since images are eigen matrices, we copy the blocks we need from the source image and save them, hence there is no need to use oiio at any point.

## Notes

Some extra modifications have been made to the `aliceVision_split360Images` software:
- the extracted images are saved on disk using a rig structure
- the "demo" mode has been renamed to "preview" mode
- the user can now specify the output image extension

These changes of the command-line and output folder structure have 2 side-effects:
- software version went from 1.0 to 2.0
- changes must be reflected in the corresponding Meshroom node.

Meshroom PR: https://github.com/alicevision/Meshroom/pull/1935

2023-03-14 10:33 UTC, servantftechnicolor commented
Although it was not introduced by this PR, i don't understand why the input and outputs are folders instead of sfmData. This make this application difficult to pipeline with the other apps.

2023-03-14 18:34 UTC, fabiencastan commented
Yes, it would be great to also generate an sfmData as suggested by @servantftechnicolor in another PR.

2023-03-14 18:35 UTC, fabiencastan requested changes
The same rig folder structure should also be used in the case of equirectangular split (not only dual-fisheye).

2023-03-15 17:39 UTC, fabiencastan commented
For another PR: when the input is a folder, we list all files and it would be good to check that the file extension is a supported image file.

2023-03-15 17:40 UTC, fabiencastan approved these changes

2023-03-15 17:40 UTC, merged