[sfmTransform] Creation of auto mode
alicevision/AliceVision pull request #1402
Opened 2023-04-04 15:07 UTC by servantftechnicolor

New sfmTransform Node

- Use cameras X axis to estimate the horizontal plane (and the horizon)
- Use GPS measurements (if available) to align the Z axis with the north
- Use GPS measurements (if available) to set the scale (otherwise scaled such that stddev=1)
- Use cameras center mean as frame origin

See https://github.com/alicevision/Meshroom/pull/1954

2023-04-06 18:59 UTC, fabiencastan commented on src/aliceVision/sfm/utils/alignment.cpp
> +    ALICEVISION_LOG_INFO("GPS point cloud scale :" << gpsCov.trace());
"GPS point cloud scale: "
Stupid formatting, but avoid space before ":" and put one after in all the places.

2023-04-07 07:44 UTC, fabiencastan commented on src/aliceVision/sfm/utils/alignment.cpp
> +        return;
```suggestion
        ALICEVISION_LOG_INFO("Scene is too small to use GPS information.");
        ALICEVISION_LOG_INFO("GPS variance is " << var << ", minimal required GPS variance is " << var << ".");
        return;
```

2023-04-12 21:48 UTC, simogasp requested changes

2023-04-12 21:48 UTC, simogasp commented on src/aliceVision/sfm/utils/alignment.cpp
> +void computeCentersMean(const sfmData::SfMData& sfmData, Vec3 & center)
Why not
```suggestion
Vec3 computeCameraCentersMean(const sfmData::SfMData& sfmData)
```

2023-04-12 21:48 UTC, simogasp commented on src/aliceVision/sfm/utils/alignment.cpp
> +        IndexT poseId = v.second->getPoseId();
```suggestion
        const auto poseId = v.second->getPoseId();
```

2023-04-12 21:48 UTC, simogasp commented on src/aliceVision/sfm/utils/alignment.cpp
> +        IndexT poseId = v.second->getPoseId();
```suggestion
        const auto poseId = v.second->getPoseId();
```

2023-04-12 21:48 UTC, simogasp commented on src/aliceVision/sfm/utils/alignment.cpp
> +    }
can be broken down into 2 functions like before, it will improve readability

2023-04-13 22:49 UTC, fabiencastan approved these changes

2023-04-14 06:16 UTC, merged