[fuseCut] Fix export debug mesh
alicevision/AliceVision pull request #1538
Opened 2023-09-18 10:16 UTC by almarouk

Exporting debug meshes for DelaunayGraphCut was deprecated due to subsequent changes in file saving functions.

This PR fixes the fore-mentioned issue by using the correct naming for exported files.

2023-09-18 10:57 UTC, almarouk commented
Related issue that can be fixed in this PR: https://github.com/alicevision/AliceVision/issues/1539

2023-10-09 15:27 UTC, servantftechnicolor requested changes

2023-10-09 15:27 UTC, servantftransperfect commented on src/aliceVision/fuseCut/DelaunayGraphCut.cpp
> +    exportFullScoreMeshs(folderName, "debug.obj");
You solve the bug in the caller where as it looks to me the bug is in the callee.

If exportDebugMesh does not work if the extension is not .obj, then it  should be enforced there ? Or at least this member should be private with comments on parameters requirements ?

2023-10-12 06:41 UTC, servantftechnicolor approved these changes

2023-10-12 06:42 UTC, servantftechnicolor commented
Maybe you can squash commits into 1 ?

2023-10-12 12:59 UTC, almarouk commented
> Maybe you can squash commits into 1 ?

Done.

2023-10-12 16:27 UTC, cbentejac approved these changes

2023-10-12 17:52 UTC, merged