Update cameraSensors.db
alicevision/AliceVision pull request #1720
Opened 2024-06-04 16:01 UTC by vladimirs04

## Description

## Features list

## Implementation remarks

2024-07-04 06:03 UTC, OmieSawie approved these changes

2024-08-20 14:49 UTC, fabiencastan commented
Do you have some links to the source of the information?

2024-09-06 20:23 UTC, fabiencastan commented
@vladimirs04 Seems to be 6.4 like the 9S:
https://www.devicespecifications.com/en/model/f53f5370
Do you have a link to the source of your information?

2024-12-23 08:43 UTC, servantftechnicolor requested changes
Value is incorrect

2025-12-27 00:11 UTC, closed without merging