change threshold for sfm validity
alicevision/AliceVision pull request #1760
Opened 2024-10-16 13:00 UTC by servantftechnicolor

Actually, sfm returns an error only if there is no reconstructed views.
We want to return an error if there is only the initial reconstructed pair and no other valid views.
If the number of views is small, we still keep 1 view as the minimal size, but for any other size, we also return an error if only 2 views are reconstructed.

2024-11-05 10:41 UTC, simogasp requested changes

2024-11-05 10:41 UTC, simogasp commented on src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
> +    if (nbviews > 5)
I would a new param to the set of parameters of the class https://github.com/alicevision/AliceVision/blob/396d82cb1e4645a9cbd40b90eac920b2e73660b6/src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.hpp#L41
(with a line of comment that explains the meaning)
Not necessary that it is exposed, but it's better than having a random number in the code.

2024-11-05 10:41 UTC, simogasp commented on src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
> +    return (nbposes >= minPoses);
```suggestion
    const auto nbviews = _sfmData.getViews().size();
    const auto nbposes = _sfmData.getPoses().size();

    const std::size_t minPoses = nbviews > small_dataset? 3 : 1;

    return (nbposes >= minPoses);
```
where `small_dataset` is the placeholder for the new param discussed above

2025-06-26 11:43 UTC, servantftransperfect commented on src/aliceVision/sfm/pipeline/sequential/ReconstructionEngine_sequentialSfM.cpp
> +    return (nbposes >= minPoses);
ok, good idea, i'll replace.

2025-10-29 10:56 UTC, closed without merging