Image segmentation cpu bugfix and onnx output update
alicevision/AliceVision pull request #1783
Opened 2024-11-22 09:20 UTC by demoulinv

## Description
This PR modifies the access to the output of the onnx model using the dedicated 'At' accessor in image segmentation. This is a safer method than accessing with a pointer because onnx does not guarantee that the allocated memory is contiguous.

It also fixes a bug when using the cpu mode by avoiding freeing cuda memory in this case.

## Features list

## Implementation remarks

2025-01-21 18:12 UTC, jgoueslard requested changes
There's just a few comments on some CUDA management with ONNXRuntime.
Please double check my comments because I am not very familiar with the code.

2025-01-21 18:12 UTC, jgoueslard commented on src/aliceVision/segmentation/segmentation.hpp
>      bool labelsFromModelOutput(image::Image<ScoredLabel>& labels, const std::vector<float>& modelOutput);
The "labelsFromModelOutput" method doesn't seem to be used anywhere in the code anymore. Am I wrong ?

2025-01-21 18:12 UTC, jgoueslard commented on src/aliceVision/segmentation/segmentation.cpp
> +        cudaAllocator.Free(_cudaInput);
Is there a specific reason why cuda memory is not handled the same way than in the SuperResolution plugin ? 
`Ort::MemoryInfo memInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);`
Link [here](https://github.ps.thmulti.com/tcs-research/ofxSuperResolution/blob/ce99bae0c393cca10c9dea8502608881bd0d29f8/src/upscaler.cpp#L515)

I think we decided to let ONNXRuntime handles the memory allocation and that the inference is made on CUDA even though it says "CPU".

2025-01-21 18:12 UTC, jgoueslard commented on src/aliceVision/segmentation/segmentation.cpp
>        mem_info_cuda, reinterpret_cast<float*>(_cudaInput), transformedInput.size(), inputDimensions.data(), inputDimensions.size());
I don't think you need to send the transformedInput to cuda manually using the cudaMemcpy method. In the SuperResolution / 2dS plugins we just give the tensor on CPU to the run method and the variable is automatically sent to CUDA

2025-01-21 18:12 UTC, jgoueslard commented on src/aliceVision/segmentation/segmentation.cpp
>        mem_info_cuda, reinterpret_cast<float*>(_cudaInput), transformedInput.size(), inputDimensions.data(), inputDimensions.size());
(I couldnt leave a comment on unmodified lines so I let it here but the wrong line is: **338**)

2025-01-21 18:12 UTC, jgoueslard commented on src/aliceVision/segmentation/segmentation.cpp
> +    if (!labelsFromOutputTensor(labels, outTensor[0]))
If my understanding is correct, it probably makes more sense to check this condition before filling the output vector

2025-01-21 18:12 UTC, jgoueslard commented on src/aliceVision/segmentation/segmentation.cpp
> +    if (!labelsFromOutputTensor(labels, outTensor[0]))
Same comment than before, this condition should probably be evaluated before filling the _output vector

2025-01-22 16:32 UTC, demoulinv commented on src/aliceVision/segmentation/segmentation.cpp
> +        cudaAllocator.Free(_cudaInput);
Memory handling updated

2025-01-22 16:32 UTC, demoulinv commented on src/aliceVision/segmentation/segmentation.cpp
>        mem_info_cuda, reinterpret_cast<float*>(_cudaInput), transformedInput.size(), inputDimensions.data(), inputDimensions.size());
Updated

2025-01-22 16:48 UTC, demoulinv commented on src/aliceVision/segmentation/segmentation.cpp
> +    if (!labelsFromOutputTensor(labels, outTensor[0]))
Done

2025-01-22 16:48 UTC, demoulinv commented on src/aliceVision/segmentation/segmentation.cpp
> +    if (!labelsFromOutputTensor(labels, outTensor[0]))
Done

2025-01-22 16:48 UTC, demoulinv commented on src/aliceVision/segmentation/segmentation.hpp
>      bool labelsFromModelOutput(image::Image<ScoredLabel>& labels, const std::vector<float>& modelOutput);
Erased!

2025-02-04 11:43 UTC, jgoueslard approved these changes
LGTM

2025-02-13 14:11 UTC, cbentejac approved these changes

2025-02-13 14:14 UTC, merged