3D-3D Registration based on PCL
alicevision/AliceVision pull request #425
Opened 2018-06-30 12:55 UTC by fabiencastan

2018-07-23 10:07 UTC, gregoire-dl commented on src/CMakeLists.txt
> +    set(FLANN_INCLUDE_DIR_HINTS ${CMAKE_CURRENT_SOURCE_DIR}/dependencies/flann/src/cpp)
`FLANN_INCLUDE_DIR_HINTS` is now set after `find_package`.
In order to find the internal one we should add another `find_package` after this line.

2019-11-21 11:15 UTC, fabiencastan commented on src/CMakeLists.txt
> +#  add_definitions("-DEIGEN_DONT_ALIGN_STATICALLY=1")
WARNING: do not merge before we have done all the changes needed for that.

2020-04-10 13:19 UTC, simogasp commented on src/aliceVision/registration/PointcloudRegistration.cpp
> +  int res = loadCloud(file, targetCloud);
const

2020-04-10 13:36 UTC, simogasp requested changes

2020-04-10 13:36 UTC, simogasp commented on src/aliceVision/registration/PointcloudRegistration.cpp
> +  auto tic = std::chrono::steady_clock::now();
use Timer

2020-04-10 13:36 UTC, simogasp commented on src/aliceVision/registration/PointcloudRegistration.cpp
> +  // load input cloud:
```c++
const auto ext =  path(inputFile).extension().toString();
if(inputFile == "ply")
...
```

2020-04-10 13:36 UTC, simogasp commented on src/aliceVision/registration/PointcloudRegistration.cpp
> +  if (outputFile.substr(outputFile.find_last_of(".") + 1) == "ply")
```c++
if(ext != "ply")
{
    ALICEVISION_LOG_ERROR("PointcloudRegistration::saveCloud: Unknown extension: " << outputFile);
    return EXIT_FAILURE;
}
pcl::io::savePLYFile(outputFile, outputCloud);
```

2020-10-02 08:33 UTC, fabiencastan commented
Check setUseSymmetricObjective:  https://github.com/PointCloudLibrary/pcl/blob/49385a6f9f37c9a1b4e4fa5f6e5b2019b90ac4b8/registration/include/pcl/registration/icp.h#L306

2020-10-02 08:49 UTC, griwodz commented
FYI, we have a quick example for using symmetric with PCL > 1.10.0 here:
https://github.com/henryhansen23/Indoor-reconstruction-plus-plus/pull/3/files

2022-09-12 16:39 UTC, simogasp commented on src/aliceVision/registration/PointcloudRegistration.cpp
> +            transform = alignGICP(mutableSourceCloud, mutableTargetCloud);
`break`? 
or is it done on purpose?

2022-09-12 18:25 UTC, fabiencastan commented on src/aliceVision/registration/PointcloudRegistration.cpp
> +            transform = alignGICP(mutableSourceCloud, mutableTargetCloud);
it seems to be a bug

2023-06-05 09:04 UTC, closed without merging