[feature] sift: update default values, add new filtering and add dsp-sift variation
alicevision/AliceVision pull request #935
Opened 2020-11-24 11:25 UTC by fabiencastan

## Description

Feature point quality has a critical impact on SfM and Panorama pipelines.
This PR re-evaluate the default parameters and add new filtering strategies to be less impacted by the peak threshold in standard sift. This parameter is critical in particular on HDR images.

## Features list

- [X] Update default sift thresholds
- [X] Add new feature points filtering
- [X] Add dsp-sift variation

## Implementation remarks

 - [X] Update vlfeat to 0.9.21
 - [X] vlfeat: build as shared library and remove init/uninit on dll load
 - [X] vlfeat: remove vlcov internal buffer to allow multi-threading (use an explicit parameter instead)

2020-11-26 16:29 UTC, servantf commented on src/aliceVision/feature/ImageDescriber.hpp
> +           "* ULTRA: Perfect quality at the expense of high computational cost.\n";
Perfect -> Best ? :p

2020-11-27 14:02 UTC, servantf submitted a review, later dismissed

2020-11-27 14:02 UTC, servantf commented on src/aliceVision/feature/sift/ImageDescriber_DSPSIFT_vlfeat.cpp
> +                    vl_covdet_extract_patch_for_frame(covdet.get(), patch.data(), kPatchResolution, &internalBuffer,
To me, this is extracting a sub image at a given location at an interpolated scale.

I assume the scale interpolation is based on the existing, pre-computed scales. So this is bounded by the parameters of the sift detector. As such, shouldn't the scales be computed to make sure that for each keypoint, we are able to  get a range of scales large enough ?

2020-11-27 15:27 UTC, simogasp requested changes

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/ImageDescriber.hpp
> +           "* ULTRA: Perfect quality at the expense of high computational cost.\n";
Highest?

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/ImageDescriber.hpp
> +           "* NoFiltering: Disable contrast filtering.\n";
what about the others?

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/ImageDescriber.hpp
> +    Static = 0,
```suggestion
    /// Use a fixed threshold for all the pixels
    Static = 0,
```
etc...

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/ImageDescriber.hpp
> +    EImageDescriberPreset descPreset = EImageDescriberPreset::NORMAL;
prefer `{}` for initialization

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/imageDescriberCommon.cpp
> +
```suggestion
  if(type == "dspsift")       return EImageDescriberType::DSPSIFT;
```

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/imageDescriberCommon.hpp
> +
```suggestion
  , DSPSIFT = 13
```

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/imageStats.hpp
> +inline float computeAutomaticContrastFactor(const image::Image<float>& image, const float percentile)
`alicevision_feature` is not a header only lib anymore, we can split the code, even if it is just one function

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/imageStats.hpp
> + * @brief Compute Contrast Factor
There are different definitions of Contrast Factor, would be better to explain briefly what is compute here

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/matching/svgVisualization.cpp
> +
```suggestion
    case feature::EImageDescriberType::DSPSIFT:        return "yellow";
```

2020-11-27 15:27 UTC, simogasp commented on src/aliceVision/feature/sift/SIFT.cpp
> +  const int firstOctave = params._firstOctave - (width*height < 5000*4000 ? 1 : 0);
would be better to refactor this as the condition is used several times in the code, better to have it in only onw place for maintenability

2020-12-01 14:05 UTC, fabiencastan commented on src/aliceVision/matching/svgVisualization.cpp
> +
I do not see the change.

2020-12-01 16:46 UTC, merged