Export distortion map in exr format
alicevision/AliceVision pull request #963
Opened 2021-01-18 14:17 UTC by servantf

- We want to export the transformation map between the origin image and the undistorted one.
- The undistorted image must contain a ROD which includes all the available pixels

2021-01-18 16:50 UTC, fabiencastan requested changes

2021-01-18 16:50 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
> +                for(int j = 0; j < int(intrinsic.h()); ++j)
You only need to test 8 pixels: corners + pixels aligned with optical center.

2021-01-18 16:50 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
> +            std::string key = std::to_string(view.getIntrinsicId());
You can keep the IndexT of the ID. No reason to convert to string.

2021-01-18 16:50 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
> +                const camera::IntrinsicBase& intrinsic = *(cam);
It would be good to put the computation of the ROI of an intrinsic in a function.

2021-01-18 16:50 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
> +void writeImageNew(const std::string& path, image::Image<image::RGBfColor>& imageIn,
Could you try to add ROI to the `writeImage` functions?

2021-01-21 12:23 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
> +void writeImageNew(const std::string& path, image::Image<image::RGBfColor>& imageIn,
This function seems to be no longer used and could be removed.

2021-01-21 12:24 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
> +            //image::writeImage(dstImage, image_ud, image::EImageColorSpace::NO_CONVERSION);
Remove commented code

2021-01-25 11:30 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
>          camera::UndistortImage(image, cam, image_ud, image::FBLACK, true); // correct principal point
We need to compute the undistort image on the full RoD.

2021-01-25 11:31 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
>          camera::UndistortImage(image, cam, image_ud, image::FBLACK, true); // correct principal point
Maybe we should add a dedicated option and always export in exr if `exportFullRoD` is enabled.

2021-01-25 11:32 UTC, fabiencastan commented on src/software/export/main_exportAnimatedCamera.cpp
>          camera::UndistortImage(image, cam, image_ud, image::FBLACK, true); // correct principal point
It would be great to also expose the option to correct the principal point (which is always enabled for now).

2021-02-19 14:29 UTC, simogasp commented on src/aliceVision/image/io.hpp
> +void writeImage(const std::string& path, const Image<float>& image, EImageColorSpace imageColorSpace,const oiio::ParamValueList& metadata = oiio::ParamValueList(),const oiio::ROI& roi = oiio::ROI());
update teh doc

2021-02-19 14:32 UTC, simogasp commented on src/software/export/main_exportAnimatedCamera.cpp
> +      "Export undistorted images with full RoD.")
maybe put explicity what ROD is instead of the acronym

2021-02-19 14:33 UTC, simogasp commented on src/software/export/main_exportAnimatedCamera.cpp
> +          else // There is distortion
```suggestion
          if(intrinsic.hasDistortion())  // There is distortion
```

2021-02-19 14:34 UTC, simogasp commented on src/software/export/main_exportAnimatedCamera.cpp
> +            oiio::ROI roiNuke = computeRoiForNuke(cam, roi, correctPrincipalPoint);
```suggestion
            const oiio::ROI roiNuke = computeRoiForNuke(cam, roi, correctPrincipalPoint);
```

2021-02-22 17:17 UTC, fabiencastan submitted a review, later dismissed

2021-02-22 19:01 UTC, fabiencastan approved these changes

2021-02-24 09:13 UTC, merged