Dev ps
alicevision/AliceVision pull request #999
Opened 2021-02-26 10:40 UTC by jmelou

2021-02-26 14:13 UTC, simogasp requested changes
please make sure you are using 4 spaces to indent the code and not tab

2021-02-26 14:13 UTC, simogasp commented on src/aliceVision/photometricStereo/photometricDataIO.cpp
> +    float x,y,z;
```suggestion

```

2021-02-26 14:13 UTC, simogasp commented on src/aliceVision/photometricStereo/photometricDataIO.cpp
> +				stream >> x >> y >> z;
```suggestion
				float x,y,z;
				stream >> x >> y >> z;
```

2021-02-26 14:13 UTC, simogasp commented on src/aliceVision/photometricStereo/photometricDataIO.cpp
> +    if (intFile.is_open())
prefer early exit conditions
```suggestion
    if (!intFile.is_open())
    {
        ALICEVIOSION_LOG_ERROR(....);
        throw ....;
    }
```

2021-02-26 14:13 UTC, simogasp commented on src/aliceVision/photometricStereo/photometricDataIO.cpp
> +		int cpt = 1;
use spaces to indent

2021-02-26 14:13 UTC, simogasp commented on src/aliceVision/photometricStereo/photometricDataIO.cpp
> +    if (dirFile.is_open())
same here

2021-02-26 14:13 UTC, simogasp commented on src/aliceVision/photometricStereo/photometricDataIO.hpp
> +#define DATAIO_HPP_INCLUDED
```suggestion
#pragma once
```

2021-02-26 14:13 UTC, simogasp commented on src/aliceVision/photometricStereo/photometricDataIO.hpp
> +#endif // DATAIO_HPP_INCLUDED
```suggestion

```

2021-02-26 14:13 UTC, simogasp commented on src/aliceVision/photometricStereo/photometricDataIO.hpp
> +void loadLightIntensities(const std::string& intFileName, const std::vector<int>& usedPictures, std::vector<std::array<float, 3>>& intList);
add doxygen documentation

2023-06-03 14:19 UTC, fabiencastan commented on src/aliceVision/lightingEstimation/lightingCalibration.cpp
> +                lightTree.put("type", "directionnal");
```suggestion
                lightTree.put("type", "directional");
```

2023-06-03 14:41 UTC, fabiencastan commented on src/aliceVision/lightingEstimation/lightingCalibration.cpp
> +                lightTree.put("type", "directionnal");
```suggestion
                lightTree.put("type", "directional");
```

2023-06-03 16:20 UTC, fabiencastan commented on src/aliceVision/lightingEstimation/lightingCalibration.cpp
> +}
??

2023-06-03 20:43 UTC, fabiencastan commented on src/aliceVision/lightingEstimation/lightingCalibration.cpp
> +}
```suggestion
```

2023-06-04 10:21 UTC, fabiencastan commented on src/aliceVision/sphereDetection/sphereDetection.hpp
> +struct prediction
CamelCase

2023-06-04 10:22 UTC, fabiencastan commented on src/software/pipeline/main_lightingCalibration.cpp
> +        std::cout << "Directory input : WIP" << std::endl;
Throw with an explicit error message.

2023-06-04 10:22 UTC, fabiencastan commented on src/software/pipeline/main_photometricStereo.cpp
> +        std::cout << "Warning : path to light data has been set to inputpath folder" << std::endl;
ALICEVISION_LOG_WARNING

2023-06-04 10:25 UTC, fabiencastan approved these changes

2023-06-04 10:26 UTC, merged